# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: '.*\.(uasset|umap|uproject|uplugin|pxd)$'
      - id: end-of-file-fixer
        exclude: '^Config/.*\.ini$|.*\.(uasset|umap|uproject|uplugin|pxd)$'
      - id: check-added-large-files
        args: ["--maxkb=102400"]
      - id: mixed-line-ending
        exclude: '.*\.(uasset|umap|uproject|uplugin|pxd)$'

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.8
    hooks:
      - id: clang-format
        types_or: [c++]
        args: [--style=file:.clang-format]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        args: ["--write", "--config", ".prettierrc"]

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: forbid-crlf
      - id: remove-crlf
      - id: forbid-tabs
        exclude: '.*\.(uasset|umap|uproject|uplugin|pxd)$|Makefile'
      - id: remove-tabs
        args: [--whitespaces-count, "4"]
        exclude: '.*\.(uasset|umap|uproject|uplugin|pxd)$|Makefile'

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        args: ["--config", "pyproject.toml"]
        exclude: '.*\.(pxd)$'
