name: Merge on Main branch

on:
  push:
    branches:
      - main
    paths:
      - "Doxyfile"
      - "Source/**/*.cpp"
      - "Source/**/*.h"
      - "**/*.py"
      - ".github/workflows/merge.yaml"

jobs:
  run-pre-commit-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Cache pre-commit environment
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Check style with pre-commit
        run: |
          pip install pre-commit
          pre-commit run --all-files

  build_documentation:
    needs: run-pre-commit-checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Doxygen and Graphviz
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      - name: Generate Documentation
        run: doxygen Doxyfile

      - name: Archive Documentation
        uses: actions/upload-artifact@v4
        with:
          name: doxygen-html
          path: Docs/html

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: DenverCoder1/doxygen-github-pages-action@v1.3.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: Docs/html
          config_file: Doxyfile
